import Phaser from 'phaser';
import { maps, enemies, dialogue, potion, root, type MapId, type EnemyId } from './data';
import { fresh, load, save, maxHp, maxMp, attack, defense, damage, gain, usePotion, type SaveState } from './state';
import './style.css';

const app=document.querySelector<HTMLDivElement>('#app')!;
app.innerHTML=`<div id="game"></div><div id="hud"></div><div id="hint"></div><div id="panel" class="hidden"></div>`;
const hud=document.querySelector<HTMLDivElement>('#hud')!,hint=document.querySelector<HTMLDivElement>('#hint')!,panel=document.querySelector<HTMLDivElement>('#panel')!;
let state:SaveState=fresh(), mode:'title'|'explore'|'dialogue'|'shop'|'menu'|'battle'|'ending'='title';
let battle:{id:EnemyId;hp:number;log:string[]}|null=null;
let scene:World|undefined, lastTravel=0, encounterDistance=0;
let selectedChoice=0;
const held=new Set<string>();
panel.addEventListener('focusin',e=>{const choices=[...panel.querySelectorAll<HTMLButtonElement>('.choices button')].filter(b=>!b.disabled);const index=choices.indexOf(e.target as HTMLButtonElement);if(index>=0)selectedChoice=index});
function focusChoice(index:number){const choices=[...panel.querySelectorAll<HTMLButtonElement>('.choices button')].filter(b=>!b.disabled);if(!choices.length)return;selectedChoice=(index+choices.length)%choices.length;choices[selectedChoice].focus()}
function choose(){const choices=[...panel.querySelectorAll<HTMLButtonElement>('.choices button')].filter(b=>!b.disabled);choices[selectedChoice]?.click()}
function back(){if(mode==='menu'||mode==='shop'){mode='explore';hide();status()}else if(mode==='dialogue')choose();else if(mode==='ending')title()}
function button(label:string,fn:()=>void,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=fn;return b}
function show(title:string,message:string,actions:HTMLButtonElement[]){panel.classList.remove('hidden');panel.replaceChildren();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=message;const row=document.createElement('div');row.className='choices';row.append(...actions);panel.append(h,p,row);focusChoice(0)}
function hide(){panel.classList.add('hidden')}
function status(){hud.textContent=mode==='title'?'':`勇者 Lv.${state.level}　HP ${state.hp}/${maxHp(state)}　MP ${state.mp}/${maxMp(state)}　${state.gold}G　薬×${state.potions}`;hint.textContent=mode==='explore'?'矢印キー: 移動　Enter/Space/Z: 話す・調べる　Esc/X: メニュー':''}
function title(){mode='title';status();show('暁の勇者','街から魔王城へ。城の竜を倒し、魔王を討て。',[button('はじめから',()=>{state=fresh();encounterDistance=0;start()}),button('つづきから',()=>{const s=load();if(s){state=s;encounterDistance=0;if(s.gameCleared)ending();else start()}},!load())])}
function start(){mode='explore';battle=null;hide();scene?.renderMap();status()}
function travel(map:MapId,x:number,y:number){if(Date.now()-lastTravel<900)return;lastTravel=Date.now();state.map=map;state.x=x;state.y=y;scene?.renderMap();status()}
function say(text:string){mode='dialogue';show('旅の記録',text,[button('つづける',()=>{mode='explore';hide();status()})]);status()}
function menu(){if(mode!=='explore')return;mode='menu';renderMenu()}
function renderMenu(){status();show('旅の支度',`経験値 ${state.xp}　回復薬 ${state.potions}個`,[button('回復薬を使う',()=>{const msg=usePotion(state);renderMenu();const p=panel.querySelector('p');if(p)p.textContent=msg}),button('セーブ',()=>{save(state);say('冒険を記録した。')}),button('戻る',()=>{mode='explore';hide();status()})])}
function interact(){if(mode!=='explore')return;const near=(x:number,y:number,r:number)=>Math.hypot(state.x-x,state.y-y)<r;
  if(state.map==='town'){for(const a of maps.town.actor_spawns||[]){if(near(a.position[0],a.position[1],115)){if(a.role==='healer'){state.hp=maxHp(state);state.mp=maxMp(state);say(dialogue.healer);return}if(a.role==='shopkeeper'){mode='shop';shop();return}say(dialogue[a.role]);return}}if(state.y>1160&&Math.abs(state.x-626)<180){travel('field',600,915);return}}
  if(state.map==='field'){if(near(600,1060,125)){travel('town',626,1080);return}if(near(687,154,130)){travel('castle',626,1080);return}if(near(780,813,95)){say('北に魔王城。南に街。');return}}
  if(state.map==='castle'){if(state.y>1150&&Math.abs(state.x-626)<180){travel('field',687,300);return}if(!state.dragonDefeated&&near(626,720,135)){startBattle('dragon');return}if(near(626,540,150)){if(!state.dragonDefeated)say('竜の結界が魔王の間を閉ざしている。先にドラゴンを倒そう。');else startBattle('dark_lord');return}}
  say('ここには何もない。')}
function shop(){status();show('道具屋',`${dialogue.shopkeeper}\n所持金 ${state.gold}G`,[button(`回復薬を買う　${potion.cost}G`,()=>{if(state.gold<potion.cost){show('道具屋','お金が足りない。',[button('戻る',shop)]);return}state.gold-=potion.cost;state.potions++;shop()},state.gold<potion.cost),button('やめる',()=>{mode='explore';hide();status()})])}
function startBattle(id:EnemyId){if(mode!=='explore')return;if(id==='dark_lord'&&!state.dragonDefeated){say('竜の結界が道をふさいでいる。');return}const e=enemies[id];encounterDistance=0;battle={id,hp:e.hp,log:[`${e.name}が現れた！`]};mode='battle';renderBattle()}
function renderBattle(){if(!battle)return;const e=enemies[battle.id];status();panel.classList.remove('hidden');panel.replaceChildren();const img=document.createElement('img');img.className='enemy';img.src=root+e.image;img.alt=e.name;panel.append(img);const h=document.createElement('h2');h.textContent=`${e.name}　HP ${battle.hp}/${e.hp}`;const p=document.createElement('p');p.className='battlelog';p.textContent=battle.log.slice(-4).join('\n');const row=document.createElement('div');row.className='choices';row.append(button('たたかう',()=>turn('attack')),button('じゅもん MP4',()=>turn('spell')),button(`どうぐ ×${state.potions}`,()=>turn('item')),button('にげる',()=>turn('run')));panel.append(h,p,row);focusChoice(selectedChoice)}
function turn(action:'attack'|'spell'|'item'|'run'){if(!battle)return;const b=battle,e=enemies[b.id];if(action==='run'){if(e.boss){b.log.push('ボスからは逃げられない！');renderBattle();return}if(Math.random()<.8){battle=null;mode='explore';hide();status();return}b.log.push('逃げられなかった！')}
  if(action==='spell'){if(state.mp<4){b.log.push('MPが足りない。');renderBattle();return}state.mp-=4;const n=damage(18+state.level*5,e.defense);b.hp-=n;b.log.push(`炎の呪文！ ${e.name}に${n}ダメージ。`)}
  if(action==='attack'){const n=damage(attack(state),e.defense);b.hp-=n;b.log.push(`勇者の攻撃！ ${e.name}に${n}ダメージ。`)}
  if(action==='item'){const msg=usePotion(state);b.log.push(msg);if(msg.includes('持っていない')||msg.includes('満タン')){renderBattle();return}}
  if(b.hp<=0){const msg=gain(state,b.id);if(b.id==='dragon'){state.dragonDefeated=true;save(state)}if(b.id==='dark_lord'){state.gameCleared=true;save(state)}battle=null;mode='dialogue';show('勝利！',`${e.name}を倒した。 ${msg}`,[button('つづける',()=>{if(state.gameCleared)ending();else{mode='explore';hide();scene?.renderMap();status()}})]);status();return}
  const n=damage(e.attack,defense(state));state.hp=Math.max(0,state.hp-n);b.log.push(`${e.name}の攻撃！ 勇者は${n}ダメージ。`);if(state.hp<=0){const lost=Math.floor(state.gold/2);state.gold-=lost;state.hp=maxHp(state);state.mp=maxMp(state);state.map='town';state.x=626;state.y=1080;battle=null;mode='dialogue';show('敗北',`${e.name}に敗れた。${lost}Gを失い、街で目を覚ました。`,[button('街へ',()=>{mode='explore';hide();scene?.renderMap();status()})]);status();return}renderBattle()}
function ending(){mode='ending';status();show('平和の夜明け','魔王は倒れ、街に平和が戻った。勇者の旅はここで幕を閉じる。',[button('タイトルへ',title)])}

class World extends Phaser.Scene {hero!:Phaser.GameObjects.Sprite; keys!:Record<string,Phaser.Input.Keyboard.Key>; objects:Phaser.GameObjects.GameObject[]=[]; lastMap:MapId|null=null; facing='down'; constructor(){super('world')}
 preload(){for(const [id,m] of Object.entries(maps)){this.load.image(`ground-${id}`,root+m.background);for(const o of m.objects)this.load.image(`obj-${id}-${o.id}`,root+o.image);if(id==='town')for(const a of m.actor_spawns||[])this.load.image(`actor-${a.role}`,root+`characters/residents/${a.role}/prop.png`)}for(const dir of ['down','up','left','right'])for(let i=1;i<=4;i++)this.load.image(`hero-${dir}-${i}`,root+`characters/hero/walk/${dir}-${i}.png`);for(const dir of ['left','right'])this.load.image(`hero-${dir}-idle`,root+`characters/hero/walk/${dir}-idle.png`);for(const id of ['dragon','dark_lord'])this.load.image(`boss-${id}`,root+enemies[id as EnemyId].image)}
 create(){scene=this;this.keys=this.input.keyboard!.addKeys('UP,DOWN,LEFT,RIGHT,W,A,S,D') as Record<string,Phaser.Input.Keyboard.Key>;for(const dir of ['down','up','left','right'])this.anims.create({key:`walk-${dir}`,frames:[1,2,3,4].map(i=>({key:`hero-${dir}-${i}`})),frameRate:8,repeat:-1});this.renderMap();this.cameras.main.setBounds(0,0,1254,1254);this.cameras.main.startFollow(this.hero,true,.12,.12);title()}
 renderMap(){if(!this.textures.exists('ground-town'))return;for(const o of this.objects)o.destroy();this.objects=[];const m=maps[state.map];this.objects.push(this.add.image(627,627,`ground-${state.map}`).setDepth(0));for(const o of m.objects){const im=this.add.image(o.center[0],o.center[1],`obj-${state.map}-${o.id}`);im.setDisplaySize(o.width,im.height*o.width/im.width);im.setDepth(o.center[1]);this.objects.push(im)}if(state.map==='town')for(const a of m.actor_spawns||[]){const im=this.add.image(a.position[0],a.position[1],`actor-${a.role}`);im.setDisplaySize(im.width*80/im.height,80).setDepth(a.position[1]);this.objects.push(im)}if(state.map==='castle'){if(!state.dragonDefeated){const d=this.add.image(626,720,'boss-dragon').setDisplaySize(150,150).setDepth(720);this.objects.push(d);const barrier=this.add.rectangle(626,625,360,15,0x8c4de0,.8).setDepth(625);this.objects.push(barrier)}const lord=this.add.image(626,540,'boss-dark_lord').setDisplaySize(130,130).setDepth(540);this.objects.push(lord)}this.hero?.destroy();this.facing='down';this.hero=this.add.sprite(state.x,state.y,'hero-down-1').setDisplaySize(100,100).setDepth(state.y+1);this.cameras.main.startFollow(this.hero,true,.12,.12);this.lastMap=state.map}
 update(_time:number,delta:number){if(mode!=='explore')return;const k=this.keys;let dx=0,dy=0;if(k.LEFT.isDown||k.A.isDown||held.has('left'))dx--;if(k.RIGHT.isDown||k.D.isDown||held.has('right'))dx++;if(k.UP.isDown||k.W.isDown||held.has('up'))dy--;if(k.DOWN.isDown||k.S.isDown||held.has('down'))dy++;if(!dx&&!dy){if(this.hero.anims.isPlaying){this.hero.anims.stop();this.hero.setTexture(this.facing==='left'||this.facing==='right'?`hero-${this.facing}-idle`:`hero-${this.facing}-1`)}return}const len=Math.hypot(dx,dy),step=Math.min(delta,50)*.2;dx=dx/len*step;dy=dy/len*step;const dir=Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up';this.facing=dir;this.hero.anims.play(`walk-${dir}`,true);const can=(x:number,y:number)=>{if(x<34||x>1220||y<34||y>1220)return false;if(state.map==='castle'&&!state.dragonDefeated&&y<635)return false;for(const o of maps[state.map].objects){if(!o.blocking||o.id==='gatehouse'||o.id==='altar')continue;const w=o.width*.55,h=Math.min(55,o.width*.22);if(Math.abs(x-o.center[0])<w/2+15&&Math.abs(y-(o.center[1]+o.width*.15))<h/2+12)return false}for(const a of maps[state.map].actor_spawns||[])if(Math.hypot(x-a.position[0],y-a.position[1])<43)return false;return true};const nx=state.x+dx,ny=state.y+dy;if(can(nx,state.y))state.x=nx;if(can(state.x,ny))state.y=ny;this.hero.setPosition(state.x,state.y).setDepth(state.y+1);
  if(state.map==='town'&&state.y>1195&&Math.abs(state.x-626)<180)travel('field',600,915);
  if(state.map==='castle'){if(state.y>1195&&Math.abs(state.x-626)<180)travel('field',687,300);else if(!state.dragonDefeated&&Math.hypot(state.x-626,state.y-720)<105)startBattle('dragon');else if(state.dragonDefeated&&Math.hypot(state.x-626,state.y-540)<100)startBattle('dark_lord')}
  if(state.map==='field'){if(Math.hypot(state.x-600,state.y-1060)<85)travel('town',626,1080);else if(Math.hypot(state.x-687,state.y-154)<95)travel('castle',626,1080);else if(state.y>200&&state.y<900){encounterDistance+=Math.hypot(dx,dy);if(encounterDistance>190&&(Math.random()<.014||encounterDistance>360))startBattle('slime')}}
 }
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:900,height:620,backgroundColor:'#171327',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{pixelArt:false},scene:[World]});
const directions:Record<string,string>={arrowup:'up',arrowdown:'down',arrowleft:'left',arrowright:'right',w:'up',s:'down',a:'left',d:'right'};
document.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(['enter',' ','z'].includes(key)){e.preventDefault();if(e.repeat)return;if(mode==='explore')interact();else choose()}else if(['escape','x'].includes(key)){e.preventDefault();if(e.repeat)return;if(mode==='explore')menu();else back()}else if(key in directions){e.preventDefault();if(mode==='explore'){held.add(directions[key]);if(!e.repeat)for(let i=0;i<3;i++)scene?.update(0,50)}else if(!e.repeat)focusChoice(selectedChoice+(['arrowup','arrowleft','w','a'].includes(key)?-1:1))}});
document.addEventListener('keyup',e=>{const dir=directions[e.key.toLowerCase()];if(dir)held.delete(dir)});
window.addEventListener('blur',()=>held.clear());
